In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('train.csv')

In [10]:
df.drop(['PassengerId','Name','Ticket'],axis = 1, inplace = True)

In [11]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [ ]:
#check data type
dtype =df.dtypes         # df.dtypes#read only function

In [12]:
class person:
    def __init__(self,name,age):
        self.name=name
        self.age = age        
    property
    def get__info(self):
        return f"my name is {self.name} and my age {self.age}"

In [13]:
p = person("mohab",21)
p.get__info

In [15]:
dtype = df.dtypes
n_uniq = df.nunique()

pd.DataFrame({
    "Dtypes": dtype,"Num_unique": n_uniq
}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes,int64,int64,object,float64,int64,int64,float64,object,object
Num_unique,2,3,2,88,7,7,248,147,3

In [16]:
def chk_types(df):
    dtype = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({ "Dtypes": dtype,"Num_unique": n_uniq})

           Dtypes  Num_unique
Survived    int64           2
Pclass      int64           3
Sex        object           2
Age       float64          88
SibSp       int64           7
Parch       int64           7
Fare      float64         248
Cabin      object         147
Embarked   object           3

In [ ]:
from python.come_back.chk_types()

In [17]:
cols = ["Pclass","SibSp","Sex","Parch","Embarked",]
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,int64,category,category,float64,category,category,float64,object,category

In [18]:
def handel_dtype(df , cols):
    df[cols] = df[cols].astype('category')
    return pd.DataFrame(df.dtypes).T

In [ ]:
print(df.shape)
print(df.shape[0])

(891, 9)
891

In [23]:
null = df.isnull().sum()
ratio = null / df.shape[0]

pd.DataFrame({"null": null, "ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [24]:
df =df.dropna(subset =["Embarked"])

In [25]:
df =df.drop("Cabin",axis =1)

In [26]:
median= df["Age"].median()
df["Age"].fillna(median,inplace=True)

C:\Users\mohab\AppData\Local\Temp\ipykernel_6156\3728883768.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(median,inplace=True)

In [27]:
pd.DataFrame({"null": null, "ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [28]:
df.describe()

         Survived         Age        Fare
count  889.000000  889.000000  889.000000
mean     0.382452   29.315152   32.096681
std      0.486260   12.984932   49.697504
min      0.000000    0.420000    0.000000
25%      0.000000   22.000000    7.895800
50%      0.000000   28.000000   14.454200
75%      1.000000   35.000000   31.000000
max      1.000000   80.000000  512.329200

In [ ]:
###############################################################################

In [ ]:
df.duplicated().sum()

In [ ]:
df.drop_duplicated().sum()

In [ ]:
num_cols =df.select_dtypes('numbers').column

In [ ]:
plt.figure(figsize=(9,2))
for i in enumerate(num_cols):
    plt.subplot(1,2, i+1)
    plt.hist(df[col],endgecolor= 'black')
    plt.title(f"{col} Distribution Graph")
plt.show()